### ISSUE TITLE
Default <abbr> styles in FF

### ISSUE THREAD

**Issue by victory-v** [pitercss/pitercss.com#11]
![screen-shot-2017-02-21-at-16 33 49- 2](https://cloud.githubusercontent.com/assets/13104389/23167157/53dc6a76-f854-11e6-93e9-1201210ab0ce.jpg)

Noticed in the last version of Mozilla Firefox.
Default `<abbr>` styles probably aren't a part of the design.

**Comment by kizu** [comment]
Was fixed awhile ago, thanks for the report!
