### ISSUE TITLE
Text in the button "Notify me" is not in middle by vertical with resolution less 1024

### ISSUE THREAD

**Issue by lutien** [pitercss/pitercss.com#13]
![screenshot-pitercss com 2017-02-22 11-45-42](https://cloud.githubusercontent.com/assets/5276969/23203713/cc171be4-f8f4-11e6-960a-9b00e1d247bd.png)
The same problem with button "Submit a Talk" on this page https://pitercss.com/call-for-speakers/
I`m not sure but may be padding-top:  .4rem; in style for .ui-Button with @media (max-width: 1023px) is not needed.

**Comment by wsjscss** [comment]
Same problem on button Submit a Talk 

![2-button](https://cloud.githubusercontent.com/assets/20801385/23248953/9e04d050-f9aa-11e6-93fd-c55905fa1789.jpg)
