### ISSUE TITLE
Знак рубля хочется отодвинуть

### ISSUE THREAD

**Issue by meritt** [pitercss/pitercss.com#22]
На кнопке в шапке знак рубля смотрится плохо, его хочется отодвинуть от цены, так же как это сделано в кнопке в контенте. И очень не хватает жирности.

<img width="179" alt="screen shot 2017-03-28 at 15 41 56" src="https://cloud.githubusercontent.com/assets/10909/24405328/29494736-13cd-11e7-98d0-8180d0ffd515.png">

**Comment by pepelsbey** [comment]
Fixed, пробелом
